### ISSUE TITLE
Add cursor: pointer; to drop downs items

### ISSUE THREAD

**Issue by Alexis-D** [mindmup/bootstrap-wysiwyg#22]
Hi,

With Firefox 20/IE 10 the items in the font/font-size drop downs don't have the pointer cursor but the (less intuitive) text one (probably because the `<a />`s don't have an `href` attribute. Anyway adding something like

``` css
.dropdown-menu a {
    cursor: pointer;
}
```

this to the CSS should do the trick.
