### ISSUE TITLE
superscript/subscript command toggle not working on Chrome

### ISSUE THREAD

**Issue by marwndev** [mindmup/bootstrap-wysiwyg#63]
I created a superscript and subscript buttons like this:  

```
<a class="btn" data-edit="subscript"><b>X<sub>2</sub></b></a>
```

On Chrome 26 when I select a text and click the button, the text is converted to subscript. When I click a second time nothing happens. The text should be reverted to normal.

It works correctly on IE10 and FF20

**Comment by benbro** [comment]
Is there a Chrome issue tracking this?

A fix:

``` css
sup {
    vertical-align: super;
}
sub {
    vertical-align: sub
}
```

http://stackoverflow.com/questions/17517839/jquery-execcommand-for-superscript-and-subscript-not-properly-toggling
